# Generated by Django 4.1.2 on 2022-10-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pelucla',
            new_name='Pelicula',
        ),
    ]
