# Generated by Django 4.1.2 on 2022-10-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_rename_pelucla_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='descipcion',
            field=models.TextField(help_text='Pon aqui una descipcion de la pelicula ', max_length=300),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
