# Generated by Django 4.1.2 on 2022-10-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_alter_pelicula_descipcion_alter_pelicula_titulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Director',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='autor',
            new_name='director',
        ),
    ]
